[package]
name = "parser-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: make it optional?
#ariadne = "0.1.5"
#codespan-reporting = "0.11"
#valuable =  { git = "https://github.com/tokio-rs/valuable/", features = ["derive"] }

[dev-dependencies]
criterion = "0.4"
insta = { version = "1", features = ["glob"] }

[[bench]]
name = "parsing"
harness = false
